### ISSUE TITLE
makefile entry point not found

### ISSUE THREAD

**Issue by ZZZ02zk** [EIE2-IAC-Labs/Lab0-devtools#5] opened 2022-10-12 20:16 UTC
I ran the test, but the result didn't came as expected, the terminal shows:

                              _**root@DESKTOP-0EEGMUO:~/Documents/iac/lab0-devtools/autumn#**_ 

and I notice that the system report "make fille entry point not found" I don't know how to fix it. 

this is screenshot:
![ok](https://user-images.githubusercontent.com/115665668/195439280-24468209-edae-4e58-a930-81cdf9c3adeb.png)

**Comment by ZZZ02zk** [comment] 2022-10-12 21:30
I think I solve the file issue, but the system reports another error, this is screen shot:
![image](https://user-images.githubusercontent.com/115665668/195451061-87a30886-cc55-40bd-b1ab-e56c8c85d7ea.png)

"#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/root/Documents/iac/lab0-devtools/autumn/workspace/toolchain/test/tb_verilator.cpp).C/C++(1696)"

do we have to download any other compilers? and do we have to add any new path in the environment variables?

**Comment by Jpnock** [comment] 2022-10-12 22:07
Vmod_test.h is created by Verilator and once created it can be found in the obj_dir folder

You should be able to create this file by running `make tb_verilator`

**Comment by ZZZ02zk** [comment] 2022-10-12 22:24
> Vmod_test.h is created by Verilator and once created it can be found in the obj_dir folder
> 
> You should be able to create this file by running `make tb_verilator`

running "make tb_verilator" ? is this a file, I didn't see any file named 'make tb_verilator'.

**Comment by Jpnock** [comment] 2022-10-12 23:46
> 

This is a command that you should run in the Ubuntu terminal (either in VS Code or via Windows Terminal). To do this you need to be in the toolchain folder and then run

```bash
cd ~/Documents/iac/lab0-devtools/autumn/workspace/toolchain/

make tb_verilator
```

The output should look as follows

```bash
user@host:~$ cd ~/Documents/iac/lab0-devtools/autumn/workspace/toolchain/

user@host:~/Documents/iac/lab0-devtools/autumn/workspace/toolchain$ make tb_verilator

==== Building Verilator test =====
position        tick    value_i value_o
(during tick)   1       42      0
(at +ve edge)   2       42      0
(during tick)   2       43      0
(at +ve edge)   3       43      42
(during tick)   3       44      42
(at +ve edge)   4       44      43
(during tick)   4       45      43
(at +ve edge)   5       45      44
(during tick)   5       46      44
Testbench exiting after reaching MAX_TICKS
```

**Comment by ZZZ02zk** [comment] 2022-10-13 00:06
> ```shell
> cd ~/Documents/iac/lab0-devtools/autumn/workspace/toolchain/
> 
> make tb_verilator
> ```
thank you so much, the output looks as expected. but the system report that 
![image](https://user-images.githubusercontent.com/115665668/195469253-f09a6d12-747c-4373-b985-59936d3b3e4e.png)

it said I need to specify the MIDebugger path, but there is no MIDebugger path in launch json

![image](https://user-images.githubusercontent.com/115665668/195469511-841c654b-68e3-4f48-8473-e9ab2bbb4889.png)

and do we have to install GDB and LLDB in Ubuntu?

**Comment by Jpnock** [comment] 2022-10-13 00:35
> > ```shell
> > cd ~/Documents/iac/lab0-devtools/autumn/workspace/toolchain/
> > 
> > make tb_verilator
> > ```
> 
> thank you so much, the output looks as expected. but the system report that ![image](https://user-images.githubusercontent.com/115665668/195469253-f09a6d12-747c-4373-b985-59936d3b3e4e.png)
> 
> it said I need to specify the MIDebugger path, but there is no MIDebugger path in launch json
> 
> ![image](https://user-images.githubusercontent.com/115665668/195469511-841c654b-68e3-4f48-8473-e9ab2bbb4889.png)
> 
> and do we have to install GDB and LLDB in Ubuntu? (and I already install the C/C++ in vscode)

gdb should be installed as part of the setup process if I remember correctly.

You could try adding the following under the line which starts with "cwd", however WSL debugging support for this doesn't appear to be great so you might not be able to get debugging this way working unfortunately (although I'll try to find a work around over the next few days). 

However, with this testbench based approach, using gdb doesn't add much value in my opinion. In the meantime, the suggested way to run the code is to run the `make tb_verilator` command which will recompile your C++ code and run the compiled executable. Have a look in `Makefile` to see what is going on when you run that command.

```
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb"
```

**Comment by ZZZ02zk** [comment] 2022-10-13 00:54
> "MIMode": "gdb",
>             "miDebuggerPath": "/usr/bin/gdb"

It still wouldn't work, I wonder "MinGW" might be the cause for the error, because I just download vs code yesterday, and I fought out that regular C++ will also fail to run for some reason, but I already install "MinGW" and add the path in the environment variable, I don't know what else I can do.

**Comment by Jpnock** [comment] 2022-10-16 21:54
Duplicate of https://github.com/EIE2-IAC-Labs/Lab0-devtools/issues/8#issuecomment-1280065175

**Closed by Jpnock** 2022-10-16 21:54 UTC
